- $unwind:
    path: $line_items
- $group:
    _id: $line_items.variant_id
    count:
      $sum: 1
    quantity:
      $sum: $line_items.quantity
    name:
      $first: $line_items.name
    title:
      $first: $line_items.title
    revenue:
      $sum:
        $toDouble: $line_items.price
    max_unit_price:
      $max:
        $toDouble: $line_items.price
    min_unit_price:
      $min:
        $toDouble: $line_items.price
- $lookup:
    from: products
    localField: _id
    foreignField: variants.id
    as: product
- $unwind:
    path: $product
    preserveNullAndEmptyArrays: true
- $addFields:
    product_type: $product.product_type
    tags: $product.tags
    vendor: $product.vendor
- $project:
    _id: 0
    product: 0
- $sort:
    quantity: -1
