- $project:
    line_items: $line_items.variant_id
- $match:
    $expr:
      $gt:
        - $size: $line_items
        - 1
- $project:
    line_items:
      $map:
        input: $line_items
        as: item
        in:
          id: $$item
          other:
            $filter:
              input: $line_items
              as: other
              cond:
                $ne:
                  - $$other
                  - $$item
- $unwind:
    path: $line_items
- $unwind:
    path: $line_items.other
- $match:
    $expr:
      $lt:
        - $line_items.other
        - $line_items.id
- $group:
    _id: $line_items
    count:
      $sum: 1
- $sort:
    count: -1
- $limit: 100
- $lookup:
    from: products
    localField: _id.id
    foreignField: variants.id
    as: p1
- $unwind:
    path: $p1
- $lookup:
    from: products
    localField: _id.other
    foreignField: variants.id
    as: p2
- $unwind:
    path: $p2
- $project:
    count: 1
    title1: $p1.title
    title2: $p2.title
